# Generated by Django 5.0.6 on 2024-07-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_alter_paciente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionDolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50)),
                ('tipo_dolor', models.CharField(max_length=50)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_dolor', to='administrativo.registro')),
            ],
        ),
    ]
