# Generated by Django 5.0.6 on 2024-07-23 22:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_ubicaciondolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciondolor',
            name='paciente',
            field=models.ForeignKey( null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_dolor', to='administrativo.paciente'),
            preserve_default=False,
        ),
    ]
