# Generated by Django 5.0.6 on 2024-07-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_ubicaciondolor_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicaciondolor',
            name='paciente',
        ),
    ]
